### ISSUE TITLE
Identify "The Self-Evolution Core"

### ISSUE THREAD

**Issue by RXien** [lurcury/lurcury#1]
initial mean is:

"iCode smart code allows the chain to self-determine its status on the chain, achieving dynamic
expansion, autonomous network monitoring and intelligent trading."

but its not precise to describe this.

**Comment by aeiou335** [comment]
I think it means that the chain will detect the current status of the environment, such as the transaction rate or the amount of the current requests and it will adjust its block size or the rate of generating a block by the information it learned. 

In the end, if the chain can learn the information and adjust itself immediately, lots of storage can be saved and also tps can be highly improved.
